### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by ituri** [guidocioni/no-more-wet-rides-new#1]
Hi,

love your project and the idea behind it. I installed all the required dependencies, added the MAPBOX_KEY and ran it via `gunicorn app:server`. However, when I try to access http://127.0.0.1:8000 I get a 404 error. Any ideas on what do do here?

Thanks!

**Comment by guidocioni** [comment]
Hi and thanks,
what does gunicorn print when it starts running? 
Did you install all the required dependencies? 
Did you try to run first the application in "debug" mode by just doing `python app.py`?

**Comment by ituri** [comment]
No error messages that couild be of any use:
```
      ~/dev/no-more-wet-rides-new    master ?1  gunicorn app:server                                                                                                                                              ✔   12:41:04   
[2021-09-03 12:41:06 +0200] [8223] [INFO] Starting gunicorn 20.1.0
[2021-09-03 12:41:06 +0200] [8223] [INFO] Listening at: http://127.0.0.1:8000 (8223)
[2021-09-03 12:41:06 +0200] [8223] [INFO] Using worker: sync
[2021-09-03 12:41:06 +0200] [8224] [INFO] Booting worker with pid: 8224
^C[2021-09-03 12:44:23 +0200] [8223] [INFO] Handling signal: int
[2021-09-03 12:44:23 +0200] [8224] [INFO] Worker exiting (pid: 8224)
[2021-09-03 12:44:24 +0200] [8223] [INFO] Shutting down: Master
      ~/dev/no-more-wet-rides-new    master ?1 ```

**Comment by guidocioni** [comment]
Ah sorry I forgot to mention!
Due to my deployment environment the application is hosted on a subpath so you have to do `127.0.0.1:8000/nmwr`. You can see that here 
https://github.com/guidocioni/no-more-wet-rides-new/blob/7684ff753c49533d81907979196324b66d1c13b0/app.py#L21

**Comment by ituri** [comment]
Oops, didn't see that. Now it's working as expected. Thank you! 😊

**Comment by guidocioni** [comment]
Nice! I haven't worked on the project for quite some time, and the code it is not really well packed, but it still seems to work so you should be good to go. 

Thanks for using it and I'm always open to suggestions ;)
